apiVersion: batch/v1
kind: Job
metadata:
  name: c2c-job1
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: c2c-latency-1
        image: docker.io/library/corelatency:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: 8
          limits:
            memory: "1Gi"
            cpu: 8
        volumeMounts:
          - name: results
            mountPath: /usr/src/myapp/bench-results
      volumes:
        - name: results
          hostPath:
            path: /home/amd/c2c-results/job1
